const fs = require('fs');
const vm = require('vm');
const path = require('path');

const root = '/Users/randy/afterclaw';
const babelPath = path.join(root, 'web/vendor/babel/babel.min.js');
const uiDir = path.join(root, 'web/ui');

const srcFiles = [
  ['tweaks-panel.jsx', 'tweaks-panel.compiled.js'],
  ['app.jsx', 'app.compiled.js'],
];

const sandbox = {
  console,
  setTimeout,
  clearTimeout,
  setInterval,
  clearInterval,
  window: {},
  self: {},
  globalThis: {},
};
sandbox.window = sandbox;
sandbox.self = sandbox;
sandbox.globalThis = sandbox;
vm.createContext(sandbox);

const babelCode = fs.readFileSync(babelPath, 'utf8');
vm.runInContext(babelCode, sandbox, { filename: 'babel.min.js' });

if (!sandbox.Babel || typeof sandbox.Babel.transform !== 'function') {
  throw new Error('Failed to load Babel standalone transform API');
}

for (const [srcName, outName] of srcFiles) {
  const srcPath = path.join(uiDir, srcName);
  const outPath = path.join(uiDir, outName);
  const code = fs.readFileSync(srcPath, 'utf8');
  const result = sandbox.Babel.transform(code, {
    presets: [
      ['env', { modules: false }],
      ['react', { runtime: 'classic' }],
    ],
    comments: false,
    compact: true,
    sourceMaps: false,
    sourceType: 'script',
    retainLines: false,
  });
  const banner = '/* Auto-generated by scripts/build_ui_compiled.js. Do not edit directly. */\n';
  fs.writeFileSync(outPath, banner + result.code + '\n', 'utf8');
  console.log(`${srcName} -> ${outName} (${Buffer.byteLength(result.code)} bytes)`);
}
