#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

BASE_URL="${FCC_BASE_URL:-http://192.168.1.30:1288}"
POOL_KEY="${FCC_POOL_KEY:-guangya}"
REMOTE="${FCC_GIT_REMOTE:-origin}"
BRANCH="${FCC_GIT_BRANCH:-}"
PUSH_ENABLED="${FCC_GIT_PUSH:-1}"

case "${POOL_KEY}" in
  guangya)
    CAPTURE_SCRIPT="${SCRIPT_DIR}/capture_guangya_pool.sh"
    LABELS="光鸭网盘, HTTP直连"
    ;;
  baidu)
    CAPTURE_SCRIPT="${SCRIPT_DIR}/capture_baidu_pool.sh"
    LABELS="百度网盘"
    ;;
  aliyun)
    CAPTURE_SCRIPT="${SCRIPT_DIR}/capture_aliyun_pool.sh"
    LABELS="阿里云盘"
    ;;
  *)
    echo "Unsupported FCC_POOL_KEY: ${POOL_KEY} (allowed: guangya|baidu|aliyun)" >&2
    exit 1
    ;;
esac

TARGET_FILE="${REPO_ROOT}/data/vendor-ip-pools/${POOL_KEY}.txt"
COMMIT_MSG="${FCC_GIT_COMMIT_MESSAGE:-chore(ip-pool): sync ${POOL_KEY} pool from ${BASE_URL}}"

echo "[1/4] Capture latest IPs from ${BASE_URL} ..."
FCC_BASE_URL="${BASE_URL}" bash "${CAPTURE_SCRIPT}"

echo "[2/4] Export app-config source_ip_pools.${POOL_KEY} -> ${TARGET_FILE} ..."
python3 - "${BASE_URL}" "${POOL_KEY}" "${TARGET_FILE}" "${LABELS}" <<'PY'
import datetime
import ipaddress
import json
import pathlib
import sys
import urllib.request

base_url, pool_key, target_file, labels = sys.argv[1:5]
url = base_url.rstrip("/") + "/api/app-config"
with urllib.request.urlopen(url, timeout=20) as resp:
    payload = json.load(resp)

cfg = payload.get("config") or payload or {}
http_cfg = cfg.get("http_service") or {}
raw_rows = ((http_cfg.get("source_ip_pools") or {}).get(pool_key, [])) or []

networks = []
seen = set()
for raw in raw_rows:
    text = str(raw or "").strip()
    if not text:
        continue
    try:
        text = str(ipaddress.ip_network(text, strict=False))
    except Exception:
        continue
    if text in seen:
        continue
    seen.add(text)
    networks.append(text)

def network_sort_key(token: str):
    net = ipaddress.ip_network(token, strict=False)
    return (net.version, int(net.network_address), net.prefixlen)

networks.sort(key=network_sort_key)

existing_networks = []
target = pathlib.Path(target_file)
if target.exists():
    for line in target.read_text(encoding="utf-8", errors="ignore").splitlines():
        text = line.strip()
        if not text or text.startswith("#") or text.startswith("//"):
            continue
        try:
            text = str(ipaddress.ip_network(text, strict=False))
        except Exception:
            continue
        existing_networks.append(text)
    existing_networks = sorted(set(existing_networks), key=network_sort_key)

if existing_networks == networks:
    print(json.dumps({
        "pool_key": pool_key,
        "network_count": len(networks),
        "target_file": str(target),
        "unchanged": True,
    }, ensure_ascii=False))
    raise SystemExit(0)

ts = datetime.datetime.utcnow().replace(microsecond=0).isoformat() + "Z"

out_lines = [
    "# Auto-generated by fcc-ip-tools",
    f"# pool: {pool_key}",
    f"# generated_at_utc: {ts}",
    f"# source_labels: {labels}",
]
out_lines.extend(networks)

target.parent.mkdir(parents=True, exist_ok=True)
target.write_text("\n".join(out_lines) + "\n", encoding="utf-8")

print(json.dumps({
    "pool_key": pool_key,
    "network_count": len(networks),
    "target_file": str(target),
}, ensure_ascii=False))
PY

echo "[3/4] Commit only ${TARGET_FILE} if changed ..."
if git -C "${REPO_ROOT}" diff --quiet -- "${TARGET_FILE}"; then
  echo "No changes detected in ${TARGET_FILE}; skip commit/push."
  exit 0
fi

git -C "${REPO_ROOT}" add "${TARGET_FILE}"
git -C "${REPO_ROOT}" commit -m "${COMMIT_MSG}" -- "${TARGET_FILE}"

if [[ -z "${BRANCH}" ]]; then
  BRANCH="$(git -C "${REPO_ROOT}" rev-parse --abbrev-ref HEAD)"
fi

if [[ "${PUSH_ENABLED}" == "1" ]]; then
  echo "[4/4] Push commit to ${REMOTE}/${BRANCH} ..."
  git -C "${REPO_ROOT}" push "${REMOTE}" "${BRANCH}"
  echo "Done."
else
  echo "[4/4] Skip push because FCC_GIT_PUSH=${PUSH_ENABLED}."
fi
